create table if not exists public.platforms (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#e8b86d',
  tagline text not null default '',
  category text not null default 'Streaming'
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references auth.users(id) on delete cascade,
  seller_name text not null,
  platform_id bigint references public.platforms(id) on delete set null,
  platform_name text not null,
  platform_color text not null default '#e8b86d',
  title text not null,
  plan_type text not null default 'Standard',
  duration_months integer not null check (duration_months > 0),
  price numeric(10, 2) not null check (price >= 0),
  original_price numeric(10, 2) not null check (original_price >= 0),
  slots_available integer not null default 1 check (slots_available >= 0),
  slots_total integer not null default 1 check (slots_total > 0),
  description text not null default '',
  features text not null default '[]',
  image_url text not null default '/images/hero-cinema.jpg',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  total numeric(10, 2) not null check (total >= 0),
  status text not null default 'confirmed',
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  payment_method text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  title text not null,
  price numeric(10, 2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  platform_name text not null,
  plan_type text not null,
  duration_months integer not null check (duration_months > 0)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null default 'General',
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  category text not null default 'General'
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null default '',
  quote text not null,
  rating integer not null default 5 check (rating between 1 and 5)
);

create index if not exists products_active_idx on public.products(is_active);
create index if not exists products_platform_idx on public.products(platform_name);
create index if not exists products_seller_idx on public.products(seller_id);
create index if not exists cart_items_user_idx on public.cart_items(user_id);
create index if not exists wishlist_items_user_idx on public.wishlist_items(user_id);
create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists reviews_product_idx on public.reviews(product_id);

alter table public.platforms enable row level security;
alter table public.products enable row level security;
alter table public.cart_items enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reviews enable row level security;
alter table public.contacts enable row level security;
alter table public.faqs enable row level security;
alter table public.testimonials enable row level security;